In [17]:
import holidays
import pandas as pd

In [36]:
uk_hols = holidays.GB(subdiv = "ENG", years = range(2012,2026))

In [37]:
uk_hols = pd.DataFrame(
    list(uk_hols.items()),
    columns = ["Date","Holiday"]
).sort_values("Date")

In [38]:
uk_hols

          Date                    Holiday
95  2012-01-01             New Year's Day
96  2012-01-02  New Year's Day (observed)
91  2012-04-06                Good Friday
99  2012-04-09              Easter Monday
92  2012-05-07                    May Day
..         ...                        ...
84  2025-05-05                    May Day
85  2025-05-26        Spring Bank Holiday
90  2025-08-25   Late Summer Bank Holiday
87  2025-12-25              Christmas Day
88  2025-12-26                 Boxing Day

[126 rows x 2 columns]

In [41]:
uk_hols

          Date                    Holiday
95  2012-01-01             New Year's Day
96  2012-01-02  New Year's Day (observed)
91  2012-04-06                Good Friday
99  2012-04-09              Easter Monday
92  2012-05-07                    May Day
..         ...                        ...
84  2025-05-05                    May Day
85  2025-05-26        Spring Bank Holiday
90  2025-08-25   Late Summer Bank Holiday
87  2025-12-25              Christmas Day
88  2025-12-26                 Boxing Day

[126 rows x 2 columns]